[package]
name = "dbce"
version = "0.1.0"
authors = ["Gabor Kecskemeti (acer) <g.kecskemeti@ljmu.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
custom_error = "1.9.2"
rand = "0.8.4"
tikv-jemallocator = "0.4.0"
reqwest = { version = "0.11.9", features = ["stream"] }
tokio = { version = "1.17.0", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["fs"] }
tokio-util = { version = "0.7.0", features = ["full"] }
futures-util = "0.3.21"
json = "0.12.4"

[profile.release]
lto = true