[package]
name = "dbce"
version = "0.1.3"
authors = ["Gabor Kecskemeti"]
edition = "2021"
default-run = "lichess"

[dependencies]
lazy_static = "1.4.0"
custom_error = "1.9.2"
rand = "0.8.5"
tikv-jemallocator = "0.5.0"
reqwest = { version = "0.11.16", features = ["stream", "json"] }
tokio = { version = "1.27.0", features = ["full"] }
tokio-stream = { version = "0.1.12", features = ["fs"] }
tokio-util = { version = "0.7.7", features = ["full"] }
futures-util = "0.3.28"
serde_json = "1.0.95"
ahash = "0.8.3"
enum-map = "2.5.0"
enumset = "1.0.12"
rustc-hash = "1.1.0"
enum-iterator = "1.4.0"
parking_lot = "0.12.1"

[profile.release]
debug = 1
lto = true
