[package]
name = "dbce"
version = "0.1.1"
authors = ["Gabor Kecskemeti (acer)"]
edition = "2021"
default-run = "lichess"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
custom_error = "1.9.2"
rand = "0.8.5"
tikv-jemallocator = "0.5.0"
reqwest = { version = "0.11.14", features = ["stream"] }
tokio = { version = "1.26.0", features = ["full"] }
tokio-stream = { version = "0.1.12", features = ["fs"] }
tokio-util = { version = "0.7.7", features = ["full"] }
futures-util = "0.3.26"
serde_json = "1.0.94"
ahash = "0.8.3"
enum-map = "2.4.2"
enumset = "1.0.12"

[profile.release]
debug = 1
lto = true
